### PR TITLE
Optimize underscore casing

### PR DESCRIPTION
**Pull request by treere**
This should optimize the undescore casing.

I made this faster because it is used during query parsing

### CODE REVIEW

**Review by lucacorti — COMMENTED** [review]
I thinks this needs to support all characters from https://jsonapi.org/format/#document-member-names-allowed-characters. So also underscore and digits.

Maabe we can leverage `Macro.underscore`? Also, in query parsing we might be able to call `resource.recase_field(name)` on the resource module and use the optimized version?

**Comment by treere** [comment]
`Macro.underscore` does not fit this case.

**Comment by lucacorti** [comment]
We are applying this to safe input because it's coming from the atoms used to describe the resource.

Anyway I'm fine with this.

**Review by lucacorti — APPROVED** [review]

**Comment by lucacorti** [comment]
@treere Do you want to merge this?

**Comment by treere** [comment]
> @treere Do you want to merge this?

I will fix merging problem soon

**Comment by treere** [comment]
There is a small bug. I'm fixing it

**Comment by lucacorti** [comment]
> There is a small bug. I'm fixing it

Any progress?

**Comment by treere** [comment]
I close this PR waiting a way to fix the bug in a clean way

**Pull request closed without merging**
